src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DW_Password__c</fullName>
        <description>DriveWealth Password</description>
        <inlineHelpText>DriveWealth Password</inlineHelpText>
        <label>DW Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DW_User_ID__c</fullName>
        <description>DriveWealth User ID</description>
        <externalId>true</externalId>
        <inlineHelpText>DriveWealth User ID</inlineHelpText>
        <label>DW User ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DW_Username__c</fullName>
        <description>DriveWealth Username</description>
        <inlineHelpText>DriveWealth Username</inlineHelpText>
        <label>DW Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/DW_Account__c.object
<CustomObject>
    <description>Object to store information about DriveWealth Accounts</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>DriveWealth Account ID</description>
        <externalId>true</externalId>
        <inlineHelpText>DriveWealth Account ID</inlineHelpText>
        <label>Account ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_No__c</fullName>
        <label>Account No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>DriveWealth accountType; 1 - Practice or 2 - Live.</description>
        <inlineHelpText>DriveWealth accountType; 1 - Practice or 2 - Live.</inlineHelpText>
        <label>Account Type</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Salesforce Account this DriveWealth account belongs to</description>
        <inlineHelpText>Salesforce Account this DriveWealth account belongs to</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DW Accounts</relationshipLabel>
        <relationshipName>DW_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DW Account</label>
    <nameField>
        <label>DW Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DataQuery.cls
/**
  * Class to build all the queries that we will be using
  * This is helpful as we will only need to keep all SOQL queries in one place in case we need to add/remove columns
  *
  * This class will also take care of CRUD/FLS as needed
 */
public with sharing class DataQuery {

    /**
      * Return DriveWealth Account List created for an Account based on Account ID
      *
      *
      * Note: Use try/catch in calling function to trap any Exceptions
      * This funciton can raise SFDCAccessControlException or Eception
      *
      * @param AccountID ID of account
      *
      * @return Account
     */

    public static Account getAccount(Id AccountId){

        //CRUD/FLS check
        Boolean hasAccountViewPermission = Util.AccessController.isAuthorizedToView(
            Schema.Account.getSobjectType(),
            new List<Schema.SobjectField>{
                    Schema.Account.fields.Name
            }
        );

        Boolean hasDWAccountViewPermission = Util.AccessController.isAuthorizedToView(
                Schema.DW_Account__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Account__c.fields.Name
                }
        );

        Account a;
        List<Account> listAcc =  [select ID, Name, (select Id, Name from DW_Accounts__r) from Account WHERE Id=:AccountId];
        if(listAcc.size() > 0 ){
            a = listAcc[0];
        }
        return a;
    }
    /**
      * Return DriveWealth Account information created for an Account based on DW Account ID
      *
      * Note: Use try/catch in calling function to trap any Exceptions
      * This funciton can raise SFDCAccessControlException or Eception
      *
      * @param AccountID ID of account
      *
      * @return DW_Account__c
     */

    public static DW_Account__c getDWAccount(Id DWAccountID){

        //CRUD/FLS check
        //Chek for DW Account
        Boolean hasDWAccountViewPermission = Util.AccessController.isAuthorizedToView(
                Schema.DW_Account__c.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.DW_Account__c.fields.Name, Schema.DW_Account__c.fields.Account__c,
                        Schema.DW_Account__c.fields.Account_ID__c, Schema.DW_Account__c.fields.Account_No__c,
                        Schema.DW_Account__c.fields.Account_Type__c
                }
        );
        //Check for account as we also need it for that
        Boolean hasAccountViewPermission = Util.AccessController.isAuthorizedToView(
                Schema.Account.getSobjectType(),
                new List<Schema.SobjectField>{
                        Schema.Account.fields.Name, Schema.Account.fields.DW_User_ID__c,
                        Schema.Account.fields.DW_Username__c, Schema.Account.fields.DW_Password__c
                }
        );
        return [select ID,Name,Account__c,Account_ID__c, Account_No__c, Account_Type__c, Account__r.DW_User_ID__c,
                        Account__r.DW_Username__c, Account__r.dW_Password__c
                    from DW_Account__c WHERE Id=:DWAccountID];
    }

}