src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DW_Password__c</fullName>
        <description>DriveWealth Password</description>
        <inlineHelpText>DriveWealth Password</inlineHelpText>
        <label>DW Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DW_Username__c</fullName>
        <description>DriveWealth Username</description>
        <inlineHelpText>DriveWealth Username</inlineHelpText>
        <label>DW Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/DriveWealth__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DriveWealth</label>
</CustomObject>

src/objects/DW_Account__c.object
<CustomObject>
    <description>Object to store information about DriveWealth Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Salesforce Account this DriveWealth account belongs to</description>
        <inlineHelpText>Salesforce Account this DriveWealth account belongs to</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DW Accounts</relationshipLabel>
        <relationshipName>DW_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DW Account</label>
    <nameField>
        <label>DW Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DW Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DW_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DW Orders</relationshipLabel>
        <relationshipName>DW_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DW_Account__c</fullName>
        <label>DW Account</label>
        <referenceTo>DW_Account__c</referenceTo>
        <relationshipLabel>DW Orders</relationshipLabel>
        <relationshipName>DW_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expires_Time_Stamp__c</fullName>
        <label>Expires Time Stamp</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instrument_ID__c</fullName>
        <label>Instrument ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instrument_Name__c</fullName>
        <label>Instrument Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Order ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>&quot;0&quot; - New, &quot;1&quot; - Partial Fill, &quot;2&quot; - Fill, &quot;4&quot; - Canceled, &quot;8&quot; - Rejected.</description>
        <inlineHelpText>&quot;0&quot; - New, &quot;1&quot; - Partial Fill, &quot;2&quot; - Fill, &quot;4&quot; - Canceled, &quot;8&quot; - Rejected.</inlineHelpText>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Fill</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Partial Fill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Market Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Side__c</fullName>
        <label>Side</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buy</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DW Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>DW Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DW Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DWOrderList_Controller_Test.cls
@isTest
private class DWOrderList_Controller_Test {

    @testSetup
    private static void doSetup(){
        //Need for API calls
        DriveWealth__c dw = new DriveWealth__c();
        dw.endpoint__c = 'http://api.drivewealth.io/v1/';
        insert dw;

        Account a = new Account();
        a.Name = 'Account A0';
        insert a;

        DW_Account__c dwAccount = new DW_Account__c();
        dwAccount.Name = 'DW Account';
        dwAccount.Account__c = a.Id;
        insert dwAccount;

        DW_Order__c dwOrder = new DW_Order__c();
        dwOrder.Account__c = a.Id;
        dwOrder.DW_Account__c = dwAccount.Id;
        dwOrder.Order_ID__c = 'OrderID';
        dwOrder.Order_Quantity__c = 12;
        dwOrder.Order_Type__c = 'Market Order';
        dwOrder.Side__c = 'Sell';
        dwOrder.Expires_Time_Stamp__c = '';
        dwOrder.Instrument_ID__c = 'instrumentID';
        dwOrder.Instrument_Name__c = 'instrument.name';
        insert dwOrder;

    }
    @istest
    private static void fetchStatus_positive() {
        Account acc = [SELECT Id, DW_Username__c, DW_Password__C from Account where name='Account A0' limit 1];
        DW_Order__c dwOrder = [select id, Order_Status__c from DW_Order__c where Account__c=:acc.Id];
        System.assertEquals('New', dwOrder.Order_Status__c);

        Map<String, Object> data = new Map<String, Object>{'mode'=>'fetchStatus', 'OrderID' => dwOrder.Id, 'AccountID'=>acc.Id};

        Test.setMock(HTTPCalloutMock.class, new HTTPMockResponse());


        Test.startTest();

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWOrderList_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        DriveWealthJsonOrderStatus retVal = (DriveWealthJsonOrderStatus)ETLC_ApexBridge_Data.decodeData(d2.output, DriveWealthJsonOrderStatus.class);

        test.stopTest();

        //API returns number so we check for 8
        System.assertEquals('8', retVal.ordStatus);

        //When saving to database, we change it to readbale form so testing for Rejected
        DW_Order__c dwOrder1 = [select id, Order_Status__c from DW_Order__c where Account__c=:acc.Id];
        System.assertEquals('Rejected', dwOrder1.Order_Status__c);
    }

    @istest
    private static void getOrders_positive() {
        Account acc = [SELECT Id, DW_Username__c, DW_Password__C from Account where name='Account A0' limit 1];
        DW_Order__c dwOrder = [select id from DW_Order__c where Account__c=:acc.Id];

        Map<String, Object> data = new Map<String, Object>{'mode'=>'getOrders', 'AccountID' => acc.Id};

        ETLC_ApexBridge_Data d1 = new ETLC_ApexBridge_Data();
        d1.operation = 'DWOrderList_Controller';
        d1.input = ETLC_ApexBridge_Data.encodeData(data);
        d1.debug = true;

        String strD2 =  ETLC_ApexBridge_Controller.execute(d1.toJson());
        ETLC_ApexBridge_Data d2 = ETLC_ApexBridge_Data.fromJSON(strD2);
        MAP<Id, DW_Order__c> retVal = (MAP<Id, DW_Order__c>)ETLC_ApexBridge_Data.decodeData(d2.output, MAP<Id, DW_Order__c>.class);
        DW_Order__c retOrder = retVal.get(dwOrder.Id);
        System.assertEquals(12, retOrder.Order_Quantity__c);
    }

    /**/
}